{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-nginx
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes auto;

    events {
      worker_connections  2048;
    }

    http {
      access_log off;
      client_max_body_size 0;
      server_tokens off;
      sendfile on;
      tcp_nopush on;

      # http 1.1 public port
      server {
        listen 81 backlog=4096;
        server_name public_http1;

        proxy_buffering off;
        proxy_http_version 1.1;
        
        location /api {
          proxy_set_header X-Jupiter-XAccel-Supported true;
          proxy_set_header X-Jupiter-Port Public;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http.sock {{- else -}} http://localhost:80 {{- end }};
        }
        location /health {
          proxy_set_header X-Jupiter-Port Public;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http.sock {{- else -}} http://localhost:80 {{- end }};
        }
        location /nginx-blobs {
          internal;
          alias {{ printf "%s/Blobs" .Values.persistence.mountPath }};
          {{ if .Values.nginx.addXAccelDebugHeader }} add_header X-Jupiter-XAccel-Used true; {{ end }}
        }

        error_page 404 @error_page;
        location @error_page {
          default_type "";
          return 200; # error_code is ignored
        }
      }

      # http 1.1 corp port
      server {
        listen 8009 backlog=4096;
        server_name corp_http1;
        
        proxy_buffering off;
        proxy_http_version 1.1;
        
        location /api {
          proxy_set_header X-Jupiter-XAccel-Supported true;
          proxy_set_header X-Jupiter-Port Corp;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http.sock {{- else -}} http://localhost:8008 {{- end }};
        }
        location /health {
          proxy_set_header X-Jupiter-Port Corp;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http.sock {{- else -}} http://localhost:8008 {{- end }};
        }
        location /nginx-blobs {
          internal;
          alias {{ printf "%s/Blobs" .Values.persistence.mountPath }};
          {{ if .Values.nginx.addXAccelDebugHeader }} add_header X-Jupiter-XAccel-Used true; {{ end }}
        }

        error_page 404 @error_page;
        location @error_page {
          default_type "";
          return 200; # error_code is ignored
        }
      }

      # public http2 port
      server {
        listen 8091 backlog=4096 http2;
        server_name public_http2;

        proxy_buffering off;
        proxy_http_version 1.1;
        
        location /api {
          proxy_set_header X-Jupiter-XAccel-Supported true;
          proxy_set_header X-Jupiter-Port Public;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http2.sock {{- else -}} http://localhost:80 {{- end }};
        }
        location /health {
          proxy_set_header X-Jupiter-Port Public;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http2.sock {{- else -}} http://localhost:80 {{- end }};
        }
        location /nginx-blobs {
          internal;
          alias {{ printf "%s/Blobs" .Values.persistence.mountPath }};
          {{ if .Values.nginx.addXAccelDebugHeader }} add_header X-Jupiter-XAccel-Used true; {{ end }}
        }

        error_page 404 @error_page;
        location @error_page {
          default_type "";
          return 200; # error_code is ignored
        }
      }

      # corp port http2
      server {
        listen 8092 backlog=4096 http2;
        server_name corp_http2;

        proxy_buffering off;
        proxy_http_version 1.1;
        
        location /api {
          proxy_set_header X-Jupiter-XAccel-Supported true;
          proxy_set_header X-Jupiter-Port Corp;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http.sock {{- else -}} http://localhost:8008 {{- end }};
        }
        location /health {
          proxy_set_header X-Jupiter-Port Corp;
          proxy_pass {{ if .Values.nginx.useDomainSockets -}} http://unix:/nginx/jupiter-http.sock {{- else -}} http://localhost:8008 {{- end }};
        }
        location /nginx-blobs {
            internal;
            alias {{ printf "%s/Blobs" .Values.persistence.mountPath }};
            {{ if .Values.nginx.addXAccelDebugHeader }}add_header X-Jupiter-XAccel-Used true; {{ end }}
        }

        error_page 404 @error_page;
        location @error_page {
          default_type "";
          return 200; # error_code is ignored
        }
      }
    }
{{ end }}
